name: "Label remover"

on:
  workflow_dispatch:
  schedule:
    - cron: '20 21 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: Stale
          type: remove
