name: 'Close stale issues and PRs'
permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue will be closed in 2 weeks in case of no activity.'
          stale-pr-message: 'This PR will be closed in 2 weeks in case of no activity.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          any-of-labels: to-check-stale
          days-before-stale: 1
          days-before-close: 1
          # debug-only: true
